In [21]:
from keras.layers import Conv3D, Activation , Dense, AveragePooling3D, MaxPooling3D , Dropout, Conv2D, MaxPooling2D
from keras.models import Sequential

from utils import *

#declaring a model
model = Sequential()
"""
#conv layer 1
L = Conv2D(5,[4,4], data_format='channels_last', activation = 'relu', input_shape=(32,32,5))
model.add(L)
#pooling
P = MaxPooling2D(pool_size=(2, 2), strides=2, padding='valid', data_format='channels_last')    
model.add(P)

#conv layer 2
output = 5
L1 = Conv2D(5,[3,3], data_format='channels_last', activation = 'relu')
model.add(L1)
#pooling
P1 = MaxPooling2D(pool_size=(2, 2), strides=2, padding='valid', data_format='channels_last')    
model.add(P1)
"""
#full connected layer
#model = model_nn(model, 26*26*5, 3, dropout=0.3, batch_normalization=True, activation='relu', neurons_decay=0, starting_power=1, l2=10**-5, compile_model=True, trainable=True)
model.add(Dense(1, name="Dense_1", activation='relu', input_shape=(32,32,5) ))
#model.add(Dropout(rate=0.3, name='Dropout_1'))
model.compile(loss=rmse_loss_keras, optimizer=keras.optimizers.Adam(), metrics=['accuracy'])
print("Ok ....")
#print(model.get_config())
#print()

Ok ....


In [22]:
batch_size = 10#128
data = '../data/csvs/galaxies/g.csv';
dir_img = '../data/images/galaxies1/all'

X_Train, Y_Train, X_Test, Y_Test, X_Valid, Y_Valid = get_train_test_valid_data_galaxy(data,dir_img,test_size=0.4, valid_size = 0.5)

history = model.fit(X_Train, Y_Train, validation_data=(X_Valid, Y_Valid), epochs=1, batch_size=batch_size, verbose=1)

save_model(model, './model.json')

plot_history(history);



Un objet de moins
-------------- Data loading ok -----------
     perte =  1
1237648702973673741

     number of images:  2599  class size : 2599
 -------- End -------
Train on 1559 samples, validate on 520 samples
Epoch 1/1


ValueError: Cannot feed value of shape (10, 1) for Tensor 'Dense_1_target:0', which has shape '(?, ?, ?, ?)'

In [12]:
plot_history_ac(history);

[[[ 1  2]
  [ 3  4]]

 [[ 9 10]
  [11 12]]

 [[ 5  6]
  [ 7  8]]]
[1 3 2]


In [ ]:
predict = model.predict(X_Test, batch_size=batch_size).reshape(-1)
metrics = metrics_with_object_class(Y_Test, predict, object_class_test, 'MLP')
metrics 

In [ ]:
plot_quality(y_test, predict, object_class_test)

In [21]:
dir_ = '../data/csvs/galaxies/'
path1 = dir_+'all1.csv'
path2 = dir_+'g.csv'
comp = 0;
with open(path1) as f:
    with open(path2,'w') as p2:
        p2.write('')
    with open(path2,'a') as p2:
        for a in f.readlines():
            p2.write(a)
            if (comp == 2600):
                break;
            else:
                comp = comp + 1

In [24]:
print(32*32*5)

5120


In [4]:
import os
#os.path.join('../data/object_images/', str(int(values['objid'])))
print(os.path.join('../data/','aaa'))

../data/aaa


In [7]:
file_csv = '../data/csvs/galaxies/g.csv';
data = pd.read_csv(file_csv, usecols=['objid','redshift']);
values = data['objid']
perte = 0
pert = ''
for v in range(len(values)):
    try:
        suffix = 'npy'
        path = os.path.join(dir_img, str(int(values[v]))+'.'+suffix)
        np.load(path)
        print('Ok')
    except :
        perte = perte + 1
        pert = pert + str(int(values[v]))+"\n"
print(perte)
print(pert)

Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
Ok
O

In [4]:
import numpy as np
a = np.array([[[1,2],[1,4]]])
b = np.array([[[1,2],[1,4]]])
c = np.array([[[1,2],[1,4]]])
d = np.array([a,b,c]);
print(d)

[[[[1 2]
   [1 4]]]


 [[[1 2]
   [1 4]]]


 [[[1 2]
   [1 4]]]]


In [1]:
from utils import *
import numpy as np
data = '../data/csvs/galaxies/g.csv';
dir_img = '../data/images/galaxies1/all'
X, Y =  load_data(data, dir_img)
#X = np.array(X)
#Y = np.array(Y)
X

Using TensorFlow backend.


Un objet de moins
-------------- Data loading ok -----------
     perte =  1
1237648702973673741

     number of images:  2599  class size : 2599
 -------- End -------


array([[[[ 0.17004971,  0.08659859,  0.12891068,  0.27372247,  0.64250898],
         [ 0.16084211,  0.08659728,  0.17092466,  0.30864012,  0.76098377],
         [ 0.17004971,  0.09321198,  0.08955635,  0.27369928,  0.3995885 ],
         ..., 
         [ 0.19718702,  0.07655293,  0.12022147,  0.28876486,  0.8076697 ],
         [ 0.18818912,  0.07989715,  0.15006608,  0.28876486,  0.66016912],
         [ 0.22370492,  0.09317722,  0.13311359,  0.26855657,  0.71180147]],

        [[ 0.15149648,  0.09650797,  0.1872026 ,  0.25835019,  0.5483923 ],
         [ 0.22370492,  0.06985919,  0.14169197,  0.29382771,  0.62436789],
         [ 0.22370492,  0.05967633,  0.19124363,  0.22157983,  0.67782503],
         ..., 
         [ 0.18818912,  0.07653879,  0.14585482,  0.23744509,  0.60569179],
         [ 0.19718702,  0.0731833 ,  0.17907125,  0.24269003,  0.52815509],
         [ 0.21494351,  0.08987021,  0.10275091,  0.24269003,  0.48700911]],

        [[ 0.19724965,  0.10305378,  0.16263336,  0.19

In [12]:
a = [np.array([1,2]), np.array([3,4]), np.array([4,5])]
b = np.array(a)
b

array([[1, 2],
       [3, 4],
       [4, 5]])

In [14]:
a = [[1,2], [3,4], [4,5]]
b = np.stack(a,axis = 0)
b

array([[1, 2],
       [3, 4],
       [4, 5]])

In [18]:
import numpy as np
X = []
Y = []
VX = []
VY = []
for i in range(100):
    X.append(np.random.randn(32, 32, 2))
    Y.append(np.random.randn(32)[0])
    VX.append(np.random.randn(32, 32, 2))
    VY.append(np.random.randn(32)[1])
print(np.array(Y).shape)
print(np.array(X).shape)

(100,)
(100, 32, 32, 2)


In [36]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import SGD

# Generate dummy data
import numpy as np

x_train = np.random.random((1000, 20,3))
y_train = keras.utils.to_categorical(np.random.randint(10, size=(1000, 1)), num_classes=10)
x_test = np.random.random((100, 20,3))
y_test = keras.utils.to_categorical(np.random.randint(10, size=(100, 1)), num_classes=10)

"""
X = []
Y = []
VX = []
VY = []
for i in range(100):
    X.append(np.random.randn(32, 32, 2))
    Y.append(np.random.randn(32)[0])
    VX.append(np.random.randn(32, 32, 2))
    VY.append(np.random.randn(32)[1])
x_train = np.array(X)
y_train = np.array(Y)
x_test = np.array(VX)
y_test = np.array(VY) """

model = Sequential()
# Dense(64) is a fully-connected layer with 64 hidden units.
# in the first layer, you must specify the expected input data shape:
# here, 20-dimensional vectors.

model.add(Dense(64, activation='relu', input_shape=(20,3,)))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy',
              optimizer=sgd,
              metrics=['accuracy'])

model.fit(x_train, y_train,
          epochs=4,batch_size=128)
#score = model.evaluate(x_test, y_test, batch_size=128)

ValueError: Error when checking target: expected dense_29 to have 3 dimensions, but got array with shape (1000, 10)

In [31]:
k = np.random.random((1000, 20, 3))
a =k.shape
a

(1000, 20, 3)